In [1]:
#pip install pandera

In [2]:
import pandera as pa
import pandas as pd

In [3]:
valores_ausentes = ['**','###!','####','****','*****','Null']
df = pd.read_csv('/home/jovyan/demo/Projeto_Jupyter/Dados_Cenipa.csv',
                 sep = ";",
                 parse_dates = ['ocorrencia_dia'],
                 dayfirst = True,
                 na_values = valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0

In [4]:
#Validação dos dados da tabela com o Pandera
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2), nullable = True),
        "ocorrencia_aerodromo": pa.Column(pa.String, nullable = True),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'([0-1]?[0-9]|[2][0-8]):([0-5][0-9]):([0-5][0-9])?$'), nullable = True),
        "total_recomendacoes": pa.Column(pa.Int)
    }
)

schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0
5751,79844,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0

In [5]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [15]:
#df.iloc[0] #Busca pelo indice
#df.iloc[-1] #Busca pelo indice do ultimo elemento
#df.loc[0] #Busca pelo label
#df.loc[:,'ocorrencia_uf'] #Busca da coluna
#df['ocorrencia_uf'] #Busca da coluna
#df.isna().sum() #Busca de elementos NA
#df.isnull().sum() #Busca de elementos Null
#df.loc[df.ocorrencia_uf.isnull()] #Valor null na coluna
#df.loc[df.ocorrencia_aerodromo.isnull()] #Valor null na coluna
#df.loc[df.ocorrencia_hora.isnull()] #Valor null na coluna
#df.count() #Conta a quantidade de elementos sem os null

In [17]:
#Ocorrências com mais de 10 recomendações

filtro = df.total_recomendacoes > 10
df.loc[filtro, 'ocorrencia_cidade']

63                 SÃO PAULO
326           RIO DE JANEIRO
530                SÃO PAULO
727                 ITÁPOLIS
872                   RECIFE
884     SÃO JOSÉ DOS PINHAIS
1062              UBERLÂNDIA
1972                BRASÍLIA
2795                  SANTOS
3930                 VITÓRIA
Name: ocorrencia_cidade, dtype: object

In [18]:
filtro = df.ocorrencia_classificacao == 'ACIDENTE'
df.loc[filtro, ['ocorrencia_cidade', 'ocorrencia_dia']]

              ocorrencia_cidade ocorrencia_dia
3            LUCAS DO RIO VERDE     2010-01-04
11                    SÃO PAULO     2010-01-10
13           PRIMAVERA DO LESTE     2010-01-11
14                       GURUPÁ     2010-01-12
15                     CANUTAMA     2010-01-15
...                         ...            ...
5737      SANTANA DO LIVRAMENTO     2020-12-23
5739                   MARITUBA     2020-12-26
5740  PRESIDENTE CASTELO BRANCO     2020-12-27
5743              RIO PARANAÍBA     2020-12-28
5745                  MATO RICO     2020-12-29

[1844 rows x 2 columns]

In [20]:
filtro1 = df.ocorrencia_classificacao == 'ACIDENTE'
filtro2 = df.ocorrencia_uf == 'PB'
df.loc[filtro1 & filtro2, ['ocorrencia_cidade', 'ocorrencia_dia']]

     ocorrencia_cidade ocorrencia_dia
953        JOÃO PESSOA     2011-08-26
1701    CAMPINA GRANDE     2012-11-23
1819    CAMPINA GRANDE     2013-01-25
1916       JOÃO PESSOA     2013-03-16
3100   PRINCESA ISABEL     2015-03-15
3510       JOÃO PESSOA     2016-01-29
4614        SANTA RITA     2018-09-02
4641         GUARABIRA     2018-09-29

In [21]:
filtro1 = df.ocorrencia_classificacao == 'ACIDENTE'
filtro2 = df.ocorrencia_uf == 'PB'
df.loc[filtro1 | filtro2, ['ocorrencia_cidade', 'ocorrencia_dia']]

              ocorrencia_cidade ocorrencia_dia
3            LUCAS DO RIO VERDE     2010-01-04
11                    SÃO PAULO     2010-01-10
13           PRIMAVERA DO LESTE     2010-01-11
14                       GURUPÁ     2010-01-12
15                     CANUTAMA     2010-01-15
...                         ...            ...
5737      SANTANA DO LIVRAMENTO     2020-12-23
5739                   MARITUBA     2020-12-26
5740  PRESIDENTE CASTELO BRANCO     2020-12-27
5743              RIO PARANAÍBA     2020-12-28
5745                  MATO RICO     2020-12-29

[1860 rows x 2 columns]

In [23]:
filtro1 = df.ocorrencia_classificacao == 'ACIDENTE'
filtro2 = (df.ocorrencia_uf == 'PB') | (df.ocorrencia_uf == 'PE')
df.loc[filtro1 & filtro2, ['ocorrencia_cidade', 'ocorrencia_dia']]

       ocorrencia_cidade ocorrencia_dia
148               RECIFE     2010-04-21
260               RECIFE     2010-07-04
424               RECIFE     2010-10-01
468            PRIMAVERA     2010-11-03
651               RECIFE     2011-02-22
821              CARUARU     2011-06-04
872               RECIFE     2011-07-13
953          JOÃO PESSOA     2011-08-26
1661              RECIFE     2012-11-02
1701      CAMPINA GRANDE     2012-11-23
1819      CAMPINA GRANDE     2013-01-25
1826              RECIFE     2013-01-27
1916         JOÃO PESSOA     2013-03-16
2041             CARUARU     2013-05-11
2085  SÃO VICENTE FERRER     2013-06-06
2916            IGARASSU     2014-11-01
2958            FLORESTA     2014-12-05
3100     PRINCESA ISABEL     2015-03-15
3409           SIRINHAÉM     2015-11-11
3510         JOÃO PESSOA     2016-01-29
3787              RECIFE     2016-10-21
4173           PETROLINA     2017-09-09
4237            IGARASSU     2017-11-11
4332              RECIFE     2018-01-23
4552    RIACHO DAS ALMAS     2018-07-16
4614          SANTA RITA     2018-09-02
4641           GUARABIRA     2018-09-29
4996               OROCÓ     2019-07-18

In [24]:
filtro1 = df.ocorrencia_classificacao == 'ACIDENTE'
filtro2 = df.ocorrencia_uf.isin (['PB', 'PE'])
df.loc[filtro1 & filtro2, ['ocorrencia_cidade', 'ocorrencia_dia']]

       ocorrencia_cidade ocorrencia_dia
148               RECIFE     2010-04-21
260               RECIFE     2010-07-04
424               RECIFE     2010-10-01
468            PRIMAVERA     2010-11-03
651               RECIFE     2011-02-22
821              CARUARU     2011-06-04
872               RECIFE     2011-07-13
953          JOÃO PESSOA     2011-08-26
1661              RECIFE     2012-11-02
1701      CAMPINA GRANDE     2012-11-23
1819      CAMPINA GRANDE     2013-01-25
1826              RECIFE     2013-01-27
1916         JOÃO PESSOA     2013-03-16
2041             CARUARU     2013-05-11
2085  SÃO VICENTE FERRER     2013-06-06
2916            IGARASSU     2014-11-01
2958            FLORESTA     2014-12-05
3100     PRINCESA ISABEL     2015-03-15
3409           SIRINHAÉM     2015-11-11
3510         JOÃO PESSOA     2016-01-29
3787              RECIFE     2016-10-21
4173           PETROLINA     2017-09-09
4237            IGARASSU     2017-11-11
4332              RECIFE     2018-01-23
4552    RIACHO DAS ALMAS     2018-07-16
4614          SANTA RITA     2018-09-02
4641           GUARABIRA     2018-09-29
4996               OROCÓ     2019-07-18

In [25]:
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
20,40310,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0
...,...,...,...,...,...,...,...,...,...
5661,79649,79649,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0
5663,79652,79652,INCIDENTE,CONFINS,MG,SBCF,2020-11-06,14:20:00,0
5680,79683,79683,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2020-11-16,22:00:00,0
5696,79692,79692,ACIDENTE,CATANDUVA,SP,SDCD,2020-11-28,12:50:00,0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0

In [26]:
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
12,40414,40414,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,03:00:00,0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
25,39772,39772,INCIDENTE,UBERLÂNDIA,MG,NaN,2010-01-20,18:58:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
...,...,...,...,...,...,...,...,...,...
5738,79787,79787,INCIDENTE,FORTALEZA,CE,SBFZ,2020-12-23,18:30:00,0
5739,79749,79749,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0
5743,79824,79824,ACIDENTE,RIO PARANAÍBA,MG,SNRP,2020-12-28,17:00:00,0
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0

In [27]:
filtro = df.ocorrencia_cidade.str[-2:] == 'NA'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
51,39115,39115,ACIDENTE,CORRENTINA,BA,SNTY,2010-02-07,17:40:00,2
81,39914,39914,INCIDENTE,LONDRINA,PR,SBLO,2010-03-09,21:00:00,0
86,39993,39993,INCIDENTE GRAVE,LONDRINA,PR,SBLO,2010-03-11,12:30:00,2
138,40328,40328,ACIDENTE,CORRENTINA,BA,NaN,2010-04-15,17:25:00,0
147,40321,40321,INCIDENTE,LONDRINA,PR,NaN,2010-04-20,16:11:00,0
...,...,...,...,...,...,...,...,...,...
5624,79582,79582,INCIDENTE,LONDRINA,PR,SBLO,2020-10-03,16:35:00,0
5631,79598,79598,ACIDENTE,ROSANA,SP,NaN,2020-10-11,11:20:00,0
5640,79620,79620,ACIDENTE,URUGUAIANA,RS,NaN,2020-10-16,14:30:00,0
5712,79725,79725,INCIDENTE,LONDRINA,PR,SBLO,2020-12-08,18:55:00,0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0

In [29]:
filtro = df.ocorrencia_cidade.str.contains('CAM')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0
34,39322,39322,ACIDENTE,SÃO BERNARDO DO CAMPO,SP,NaN,2010-01-26,13:50:00,2
44,39748,39748,INCIDENTE,CAMBÉ,PR,NaN,2010-02-03,14:30:00,0
55,39178,39178,INCIDENTE,CAMPINAS,SP,NaN,2010-02-08,12:33:00,0
76,40331,40331,INCIDENTE,CAMPINAS,SP,NaN,2010-02-28,09:00:00,0
...,...,...,...,...,...,...,...,...,...
5623,79588,79588,INCIDENTE,CAMPINAS,SP,SBKP,2020-10-02,10:50:00,0
5633,79601,79601,INCIDENTE,SÃO JOSÉ DOS CAMPOS,SP,SBSJ,2020-10-14,12:06:00,0
5649,79634,79634,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,NaN,2020-10-26,15:57:00,0
5661,79649,79649,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0

In [31]:
filtro = df.ocorrencia_cidade.str.contains('CAM | AL')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
130,40258,40258,INCIDENTE,MONTE ALEGRE,PA,NaN,2010-04-12,18:10:00,0
131,40327,40327,INCIDENTE,PORTO ALEGRE,RS,NaN,2010-04-12,13:13:00,0
133,40248,40248,INCIDENTE,PORTO ALEGRE,RS,SBPA,2010-04-13,18:47:00,0
156,40572,40572,ACIDENTE,PORTO ALEGRE,RS,SBPA,2010-04-28,14:10:00,0
192,41054,41054,INCIDENTE,MONTE ALEGRE,PA,NaN,2010-05-18,14:55:00,0
...,...,...,...,...,...,...,...,...,...
5485,79472,79472,INCIDENTE,ALTO ALEGRE,RR,SJYG,2020-06-17,22:10:00,0
5652,79645,79645,ACIDENTE,ALTO ALEGRE,RR,NaN,2020-10-28,12:25:00,0
5659,79647,79647,INCIDENTE,PORTO ALEGRE,RS,SBPA,2020-11-01,18:20:00,0
5682,79684,79684,INCIDENTE,PORTO ALEGRE,RS,SBPA,2020-11-17,20:18:00,0
5733,79759,79759,INCIDENTE,PORTO ALEGRE,RS,SBPA,2020-12-21,23:14:00,0

In [32]:
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2996,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3
2997,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
2998,53073,53073,INCIDENTE,TEFÉ,AM,SBTF,2015-01-02,16:28:00,0
2999,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0
3000,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6
...,...,...,...,...,...,...,...,...,...
3462,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
3463,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3464,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3465,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
3466,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [40]:
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
filtro3 = df.ocorrencia_dia.dt.day == 8
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [41]:
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
filtro3 = (df.ocorrencia_dia.dt.day > 2) & (df.ocorrencia_dia.dt.day < 9)
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [46]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

In [48]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,2010-01-05 19:25:00

In [50]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [53]:
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 14:30:00'

df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,2015-12-06 13:10:00
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1,2015-12-08 14:30:00
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [56]:
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3

df20153 = df.loc[filtro1 & filtro2]

df20153

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3086,53183,53183,ACIDENTE,AMAPORÃ,PR,NaN,2015-03-02,23:00:00,0,2015-03-02 23:00:00
3087,53120,53120,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0,2015-03-04 13:30:00
3088,53109,53109,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0,2015-03-05 13:50:00
3089,53112,53112,ACIDENTE,MOGI GUAÇU,SP,NaN,2015-03-06,21:00:00,0,2015-03-06 21:00:00
3090,53152,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2,2015-03-10 11:30:00
3091,53167,53167,INCIDENTE,MARABÁ,PA,SBMA,2015-03-10,17:33:00,0,2015-03-10 17:33:00
3092,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,2015-03-10 21:35:00
3093,53149,53149,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0,2015-03-11 23:25:00
3094,53148,53148,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0,2015-03-12 12:40:00
3095,53153,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,2015-03-13 15:45:00
3096,53154,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,2015-03-13 14:40:00
3097,53238,53238,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0,2015-03-13 11:30:00
3098,53189,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,07:20:00,0,2015-03-14 07:20:00
3099,53193,53193,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0,2015-03-14 18:00:00
3100,53164,53164,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0,2015-03-15 18:30:00
3101,53151,53151,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1,2015-03-16 18:07:00
3102,53168,53168,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,2015-03-16 21:05:00
3103,53169,53169,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,03:25:00,0,2015-03-19 03:25:00
3104,53165,53165,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,NaN,2015-03-20,14:35:00,0,2015-03-20 14:35:00
3105,53188,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,2015-03-20 21:00:00
3106,53184,53184,ACIDENTE,PORTO UNIÃO,SC,NaN,2015-03-22,13:44:00,0,2015-03-22 13:44:00
3107,53178,53178,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0,2015-03-23 17:15:00
3108,53182,53182,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0,2015-03-23 20:40:00
3109,53166,53166,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0,2015-03-24 14:45:00
3110,53170,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,2015-03-24 17:57:00
3111,53185,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,2015-03-24 23:01:00
3112,53412,53412,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2015-03-24,16:35:00,0,2015-03-24 16:35:00
3113,53194,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,2015-03-26 20:30:00
3114,53186,53186,INCIDENTE,BRASÍLIA,DF,NaN,2015-03-27,14:55:00,0,2015-03-27 14:55:00
3115,53179,53179,ACIDENTE,CAIAPÔNIA,GO,NaN,2015-03-28,10:30:00,0,2015-03-28 10:30:00
3116,53180,53180,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0,2015-03-28 18:52:00
3117,53190,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,2015-03-28 16:26:00
3118,53212,53212,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0,2015-03-28 17:32:00
3119,53213,53213,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0,2015-03-28 15:51:00
3120,53181,53181,ACIDENTE,COLÍDER,MT,NaN,2015-03-29,20:17:00,0,2015-03-29 20:17:00
3121,53187,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,2015-03-29 18:36:00
3122,53211,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,2015-03-30 19:40:00

In [57]:
df20153.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [59]:
#df20153.groupby(['codigo_ocorrencia']).count()
df20153.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [60]:
df20153.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count() #Errado devido aos valores Null

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [62]:
df20153.groupby(['ocorrencia_classificacao']).size().sort_values(ascending = False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [63]:
filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP','MG','RJ','ES'])

dfsudeste2010 = df.loc[filtro1 & filtro2]

dfsudeste2010

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0,2010-01-10 20:00:00
11,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8,2010-01-10 14:50:00
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0,2010-01-15 15:00:00
...,...,...,...,...,...,...,...,...,...,...
541,43722,43722,ACIDENTE,CAJOBI,SP,NaN,2010-12-23,11:00:00,0,2010-12-23 11:00:00
544,43548,43548,INCIDENTE,SÃO PAULO,SP,SBSP,2010-12-26,22:10:00,0,2010-12-26 22:10:00
548,43724,43724,ACIDENTE,COSMÓPOLIS,SP,NaN,2010-12-29,12:00:00,0,2010-12-29 12:00:00
550,43730,43730,INCIDENTE,VITÓRIA,ES,NaN,2010-12-30,18:10:00,0,2010-12-30 18:10:00
551,43975,43975,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0,2010-12-30 14:28:00

In [64]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            40
INCIDENTE          170
INCIDENTE GRAVE     18
dtype: int64

In [65]:
dfsudeste2010.count()

codigo_ocorrencia           228
codigo_ocorrencia2          228
ocorrencia_classificacao    228
ocorrencia_cidade           228
ocorrencia_uf               228
ocorrencia_aerodromo        127
ocorrencia_dia              228
ocorrencia_hora             228
total_recomendacoes         228
ocorrencia_dia_hora         228
dtype: int64

In [67]:
dfsudeste2010.groupby(['ocorrencia_classificacao', 'ocorrencia_uf']).size().sort_values(ascending = False)

ocorrencia_classificacao  ocorrencia_uf
INCIDENTE                 SP               74
                          RJ               52
                          MG               39
ACIDENTE                  SP               24
                          RJ                9
INCIDENTE GRAVE           SP                9
ACIDENTE                  MG                7
INCIDENTE                 ES                5
INCIDENTE GRAVE           MG                5
                          RJ                4
dtype: int64

In [68]:
dfsudeste2010.groupby(['ocorrencia_uf', 'ocorrencia_classificacao']).size().sort_values(ascending = False)

ocorrencia_uf  ocorrencia_classificacao
SP             INCIDENTE                   74
RJ             INCIDENTE                   52
MG             INCIDENTE                   39
SP             ACIDENTE                    24
RJ             ACIDENTE                     9
SP             INCIDENTE GRAVE              9
MG             ACIDENTE                     7
ES             INCIDENTE                    5
MG             INCIDENTE GRAVE              5
RJ             INCIDENTE GRAVE              4
dtype: int64

In [69]:
dfsudeste2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending = False)

ocorrencia_cidade
RIO DE JANEIRO           47
SÃO PAULO                33
GUARULHOS                18
BELO HORIZONTE           17
CAMPINAS                 13
MACAÉ                    12
CONFINS                   7
UBERLÂNDIA                5
JUIZ DE FORA              4
VITÓRIA                   4
MARÍLIA                   3
SÃO JOSÉ DOS CAMPOS       3
SÃO JOSÉ DO RIO PRETO     3
SOROCABA                  2
ITANHAÉM                  2
RIBEIRÃO PRETO            2
IPATINGA                  2
POÇOS DE CALDAS           2
DIVINÓPOLIS               2
BAURU                     2
JUNDIAÍ                   2
ARARAQUARA                2
CAMPOS DOS GOYTACAZES     2
AREALVA                   2
MONTES CLAROS             2
UBERABA                   2
POUSO ALEGRE              1
PIRACICABA                1
PIRASSUNUNGA              1
ARRAIAL DO CABO           1
RESENDE                   1
PENÁPOLIS                 1
SANTOS                    1
SERRA NEGRA               1
SÃO BERNARDO DO CAMPO     1
TIMÓTEO                   1
ARAÇATUBA                 1
PIACATU                   1
BOM JESUS DO AMPARO       1
PARÁ DE MINAS             1
OLÍMPIA                   1
BRAGANÇA PAULISTA         1
BROTAS                    1
CAJOBI                    1
CAMANDUCAIA               1
BOITUVA                   1
CASIMIRO DE ABREU         1
BOCAINA                   1
COROMANDEL                1
COSMÓPOLIS                1
DIAMANTINA                1
BEBEDOURO                 1
IPERÓ                     1
ITÁPOLIS                  1
LINHARES                  1
MANGARATIBA               1
BOM JESUS DO GALHO        1
NOVO HORIZONTE            1
AMERICANA                 1
dtype: int64